function videoSettings = configure_video_settings()
    % Function to configure video processing settings
    videoSettings = struct('manualROIselection',  false, ...
                           'isSTDmaskingOn',  true, ...
                           'stdCoef', 1.5, ... 
                           'isHSVmaskingOn',  true, ... %turned to false 
                           'hsvMin', [0.00, 0.09, 0.34], ...
                           'hsvMax', [0.13, 0.52, 1.00], 'cascadeROIselection', true); %added the cascadeROIselection to call the viola-jones algorithm 
end
