function ippgSettings = configure_ippg_settings(VIDEO_SR)
    % Function to configure iPPG settings based on video sampling rate
    if nargin < 1
        VIDEO_SR = 30; % Default value if VIDEO_SR is not provided
    end
    
    % Determine FFT window size based on the video sampling rate
    if (VIDEO_SR > 50)
        FFT_WINDOW_SIZE = 2048; 
    elseif (VIDEO_SR > 25)
        FFT_WINDOW_SIZE = 1024; 
    else
        FFT_WINDOW_SIZE = 512; 
    end
    
    ippgSettings = struct('PROCESSING', struct('SPA_DETRENDING', 2^0, ...
                                               'PRE_MA_FILTER', 2^1, ...
                                               'PRE_BANDPASS_FILTER', 2^2, ...
                                               'POST_MA_FILTER', 2^3, ...
                                               'POST_BANDPASS_FILTER', 2^4, ...
                                               'OUTLIERS_SUPPRESSION', 2^5, ...
                                               'POST_WAVELET_FILTER', 2^6, ...                                                
                                               'ADAPTIVE_BAND_FILTER', 2^7), ...
                          'EXTRACTION', struct('GREEN', 1, ...
                                               'ICA', 2, ...
                                               'CHROM', 3, ...
                                               'POS', 4, ...
                                               'G_MINUS_R', 5, ...
                                               'AGRD', 6), ...                                                 
                      'minFreq', 0.65, ...
                      'maxFreq', 4.00, ...                    
                      'samplingRate', VIDEO_SR, ...                    
                      'processing', 0, ...
                      'extractionMethod', 0, ...  
                      'maFilterLength', 5, ...
                      'bandpassFilterOrder', 127, ... 
                      'stdWindowLength', fix(VIDEO_SR), ...
                      'waveletFilterWidth', [2, 5], ... 
                      'waveletFilterAveragingLength', 20 * VIDEO_SR, ...                 
                      'fftWindow', FFT_WINDOW_SIZE, ...
                      'fftShiftSize', ceil(FFT_WINDOW_SIZE / 2));
% ippgSettings.processing = [ippgSettings.PROCESSING.PRE_BANDPASS_FILTER, ...
%                            ippgSettings.PROCESSING.PRE_MA_FILTER, ...
%                            ippgSettings.PROCESSING.POST_BANDPASS_FILTER
%                            ];
     
ippgSettings.processing = [ippgSettings.PROCESSING.OUTLIERS_SUPPRESSION,...
                             ippgSettings.PROCESSING.POST_BANDPASS_FILTER ];                     
ippgSettings.extractionMethod = 'CHROM';

    % Original Settings

end

